// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbbcqbvnbtptyuczzecm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiYmNxYnZuYnRwdHl1Y3p6ZWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzM5MzEsImV4cCI6MjA2NzIwOTkzMX0.kaXwFhLG-cjn9gAfFQmGl0Uuj53GaGrgmsT2GQ2jV7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});